library(data.table)
setwd("D:/Priyanka/Coursera/4.EDA/assignment1/")
data <- fread("household_power_consumption.txt", header = TRUE, sep=';' ,na.strings = "?", colClasses = c("character","character",rep("numeric",7)))
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data_1 <- data[Date >= '2007-02-01' & Date <='2007-02-02']
data_1$DateTime <- paste(as.Date(data_1$Date), data_1$Time)
data_1$DateTime <- as.POSIXct(data_1$DateTime)
par(mfrow=c(1,1))
hist(data_1$Global_active_power, col = "red", xlab = "Global Active Power(Kilowatts)",main = "Global Active Power")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()
